name: (Release) Build and Push Default CompreFace version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g., 1.0.0)
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Build images
        env:
          VERSION: ${{ github.event.inputs.version }}
          #APPERY_API_KEY: ${{ secrets.APPERY_API_KEY }}
        working-directory: ./dev/
        run: |
          sed -i 's/latest/${VERSION}/g' .env
          docker-compose build
          docker images

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Push images to Docker Hub
        working-directory: ./dev/
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          docker-compose push